Repository jupyterhub/kubespawner, pull requests merged in 2020-10, with the labels that each got.

#382 Delete remnant now unused parts in spawner.py
  kubespawner/spawner.py
Labels: maintenance

#445 Manage regexp syntax deprecation
  kubespawner/objects.py
Labels: maintenance

#442 Allow image_pull_secrets config to be specified the k8s native way
  kubespawner/objects.py
  kubespawner/spawner.py
  tests/test_objects.py
  tests/test_spawner.py
Labels: enhancement

#444 Python 3.6+ migration: async in 3.5 and async with yeild in 3.6
  kubespawner/proxy.py
  kubespawner/spawner.py
  tests/test_spawner.py
Labels: maintenance

#443 changelog: preparations for 0.14.0
  docs/source/changelog.md
Labels: documentation

#451 KubeSpawner.image_pull_secrets malfunctions in 0.14.0 - this fixes it
  kubespawner/spawner.py
  tests/test_spawner.py
Labels: bug

#455 Cleanup JS patch of JupyterHub 0.8 HTML not needed in 0.9+
  kubespawner/spawner.py
Labels: maintenance

#453 Let uid/gid/fs_gid default to None instead of 0
  kubespawner/spawner.py
  tests/test_objects.py
  tests/test_spawner.py
Labels: breaking, bug
