Repository jupyterhub/kubespawner, pull requests merged in 2021-03, with the labels that each got.

#489 fix url-change detection in poll
  kubespawner/spawner.py
  tests/test_spawner.py
Labels: bug

#495 Add MANIFEST.in (LICENCE, README.md)
  MANIFEST.in
Labels: maintenance

#477 Add options_from_form as configurable
  kubespawner/spawner.py
Labels: enhancement

#494 Fix 492 -- config kubernetes client ssl_ca_cert
  kubespawner/clients.py
  kubespawner/proxy.py
  kubespawner/reflector.py
  kubespawner/spawner.py
Labels: enhancement
