Repository jupyterhub/kubespawner, pull requests merged in 2021-11, with the labels that each got.

#538 docs: require sphinx >=2
  docs/requirements.txt
Labels: ci

#511 Fix race condition between spawn() calling _start() and progress()
  kubespawner/spawner.py
Labels: bug

#540 Add changelog for 1.1.2
  docs/source/changelog.md
Labels: documentation

#545 Default allow_privilege_escalation to False
  kubespawner/objects.py
  kubespawner/spawner.py
  tests/test_objects.py
Labels: bug, breaking

#551 Fix a comment mistake for spawner.py
  kubespawner/spawner.py
Labels: documentation

#547 Add changelog for KubeSpawner 2.0.0
  docs/source/changelog.md
Labels: documentation
