Repository jupyterhub/kubespawner, pull requests merged in 2021-05, with the labels that each got.

#502 Rewrite help for Kubespawner.cmd
  kubespawner/spawner.py
Labels: documentation

#475 add method to delete namespaced PVC in spawner base class
  kubespawner/spawner.py
  tests/test_spawner.py
Labels: breaking, new

#507 Add changelog for 1.0.0
  docs/source/changelog.md
Labels: documentation

#508 Remove unneeded dep
  setup.py
Labels: maintenance
