Repository jupyterhub/kubespawner, pull requests merged in 2021-02, with the labels that each got.

#481 Fix failure to create a PVC being logged as failure to create a Pod
  kubespawner/spawner.py
Labels: bug

#482 pre-commit: use prettier as autoformatter (markdown, yaml)
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  .readthedocs.yml
  CONTRIBUTING.md
  README.md
  RELEASE.md
  docs/environment.yml
  docs/requirements.txt
  docs/source/changelog.md
  docs/source/overview.md
Labels: maintenance

#403 [KubeIngressProxy] allow singleuser pods to use IPv6 addresses
  kubespawner/objects.py
  tests/test_objects.py
Labels: KubeIngressProxy

#484 fix KubeIngressProxy for #458
  kubespawner/proxy.py
Labels: KubeIngressProxy

#476 Allow mounting of service account token to be configurable (automount_service_account_token)
  kubespawner/objects.py
  kubespawner/spawner.py
  tests/test_objects.py
Labels: enhancement

#408 handle pod url changes in poll
  kubespawner/spawner.py
Labels: bug
