Repository jupyterhub/kubespawner, pull requests merged in 2022-02, with the labels that each got.

#562 Add changelog for 2.0.1
  docs/source/changelog.md
Labels: documentation

#563 Rely on the event loop: use `kubernetes_asyncio` instead of `kubernetes` and dedicated threads
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  kubespawner/clients.py
  kubespawner/objects.py
  kubespawner/proxy.py
  kubespawner/reflector.py
  kubespawner/spawner.py
  pyproject.toml
  setup.cfg
  setup.py
  tests/conftest.py
  tests/test_multi_namespace_spawner.py
  tests/test_objects.py
  tests/test_spawner.py
  tests/test_utils.py
Labels: maintenance, breaking

#576 Simplify async init
  kubespawner/clients.py
  kubespawner/proxy.py
  kubespawner/reflector.py
  kubespawner/spawner.py
Labels: maintenance

#579 close shared clients when loop closes
  kubespawner/clients.py
  kubespawner/reflector.py
  tests/conftest.py
  tests/test_clients.py
  tests/test_multi_namespace_spawner.py
  tests/test_spawner.py
Labels: bug
