Repository jupyterhub/kubespawner, pull requests merged in 2022-08, with the labels that each got.

#624 ci: add dependabot to bump github action versions, and bump them
  .github/dependabot.yml
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
Labels: ci

#635 catch errors in reflector.start
  kubespawner/reflector.py
  kubespawner/spawner.py
Labels: bug

#636 Add changelog for 4.2.0
  docs/source/changelog.md
Labels: documentation
