Repository jupyterhub/kubespawner, pull requests merged in 2022-11, with the labels that each got.

#661 ci: misc ci updates
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
Labels: ci

#663 Add changelog for 4.3.0
  docs/source/changelog.md
Labels: documentation

#664 Make sure we run the publish workflow on every tag pushed
  .github/workflows/publish.yaml
Labels: ci

#655 [KubeIngressProxy] Add ingress_extra_annotations and ingress_extra_labels
  kubespawner/objects.py
  kubespawner/proxy.py
  tests/test_objects.py
Labels: new

#668 [KubeIngressProxy] Add KubeIngressProxy.ingress_class_name
  kubespawner/objects.py
  kubespawner/proxy.py
  tests/test_objects.py
Labels: KubeIngressProxy, new

#642 Expand environment variables
  .gitignore
  docs/source/changelog.md
  kubespawner/spawner.py
  tests/test_spawner.py
Labels: breaking

#666 maint: pyproject.toml, hatchling, tbump, .readthedocs.yaml updates
  .bumpversion.cfg
  .flake8
  .readthedocs.yaml
  RELEASE.md
  kubespawner/__init__.py
  kubespawner/_version.py
  pyproject.toml
  setup.py
Labels: maintenance

#670 docs: fix bullet lists in profile_list
  kubespawner/spawner.py
Labels: documentation

#671 docs: fix typo in release.md
  RELEASE.md
Labels: documentation

#654 Fix hard-coded component label for services_enabled=True
  kubespawner/objects.py
  kubespawner/spawner.py
  tests/conftest.py
  tests/test_spawner.py
Labels: bug

#672 Avoid class state by passing relevant config to PodReflector on instanciation
  kubespawner/spawner.py
Labels: maintenance

#667 [KubeIngressProxy] Add KubeIngressProxy.ingress_specifications
  kubespawner/objects.py
  kubespawner/proxy.py
  kubespawner/utils.py
  tests/test_objects.py
Labels: KubeIngressProxy, new

#673 docs: relocate docs/requirements.txt into pyproject.toml
  .github/workflows/test.yaml
  .readthedocs.yaml
  CONTRIBUTING.md
  docs/requirements.txt
  pyproject.toml
Labels: documentation

#683 docs: stick with docs/requirements.txt
  .readthedocs.yaml
  CONTRIBUTING.md
  docs/requirements.txt
  pyproject.toml
Labels: documentation

#684 docs: run rst2myst
  docs/source/changelog.md
  docs/source/objects.md
  docs/source/objects.rst
  docs/source/reflector.md
  docs/source/reflector.rst
  docs/source/spawner.md
  docs/source/spawner.rst
  docs/source/utils.md
  docs/source/utils.rst
Labels: documentation
