Repository jupyterhub/kubespawner, pull requests merged in 2022-03, with the labels that each got.

#571 Misc maintenance details
  .flake8
  docs/source/conf.py
  kubespawner/__init__.py
  kubespawner/objects.py
  kubespawner/proxy.py
  kubespawner/reflector.py
  kubespawner/spawner.py
  kubespawner/traitlets.py
  setup.py
  tests/conftest.py
  tests/test_multi_namespace_spawner.py
  tests/test_spawner.py
  tests/test_utils.py
Labels: maintenance

#575 Replace recommonmark with myst_parser and fix changelog rendering
  docs/requirements.txt
  docs/source/conf.py
  kubespawner/spawner.py
Labels: maintenance

#572 Add underscore prefix to private functions: `safe_name_for_routespec` and `delete_if_exists`
  kubespawner/proxy.py
Labels: maintenance, breaking

#584 Please flake8 by removing unused imports
  kubespawner/proxy.py
  kubespawner/spawner.py
  tests/test_multi_namespace_spawner.py
Labels: maintenance

#568 Add a long docstring to KubeIngressProxy class
  kubespawner/proxy.py
Labels: documentation

#581 Add changelog for 3.0.0
  docs/source/changelog.md
Labels: documentation

#588 Add changelog for 3.0.1
  docs/source/changelog.md
Labels: documentation

#591 DOCS: Update theme to use book theme
  docs/requirements.txt
  docs/source/changelog.md
  docs/source/conf.py
  docs/source/index.md
  docs/source/index.rst
  docs/source/traitlets.rst
  kubespawner/utils.py
Labels: documentation

#593 [KubeIngressProxy] Fix critical regression from typo
  kubespawner/proxy.py
Labels: bug, KubeIngressProxy

#595 Add changelog for 3.0.2
  docs/source/changelog.md
Labels: documentation

#599 ci: stop testinging 1.17-1.19, assume k8s 1.20+ going onwards
  .github/workflows/test.yaml
Labels: breaking, ci
