Repository jupyterhub/kubespawner, pull requests merged in 2023-04, with the labels that each got.

#713 dependabot: monthly updates of github actions
  .github/dependabot.yaml
Labels: maintenance

#650 Let `kubespawner_override` merge instead of replace dictionaries
  docs/source/changelog.md
  kubespawner/spawner.py
  kubespawner/utils.py
  tests/test_spawner.py
Labels: bug, breaking

#678 Allow to watch multiple namespaces at the same time
  kubespawner/spawner.py
  tests/conftest.py
  tests/test_multi_namespace_spawner.py
  tests/test_spawner.py
Labels: new

#680 Update docs on setting up a development environment
  CONTRIBUTING.md
Labels: documentation

#718 Drop support for k8s 1.20-1.22 (stop testing against it)
  .github/workflows/test.yaml
  docs/source/changelog.md
  pyproject.toml
Labels: maintenance, breaking

#721 docs: add changelog for 5.0.0
  docs/source/changelog.md
  docs/source/conf.py
  kubespawner/proxy.py
  kubespawner/spawner.py
Labels: documentation
