Repository jupyterhub/kubespawner, pull requests merged in 2023-11, with the labels that each got.

#807 Omit ImagePullPolicy by default
  kubespawner/objects.py
  kubespawner/spawner.py
  tests/test_objects.py
Labels: bug

#808 update_k8s_model: log override at info not warn
  kubespawner/utils.py
  tests/test_utils.py
Labels: maintenance

#790 docs: add detail to internal_ssl + fix typos
  README.md
  docs/source/index.md
  docs/source/ssl.md
Labels: documentation

#809 docs: fix outdated k8s api reference links
  kubespawner/objects.py
  kubespawner/reflector.py
  kubespawner/spawner.py
  tests/test_objects.py
Labels: documentation

#810 ci: update python and k8s versions to test with, include py312
  .github/workflows/test.yaml
Labels: ci
