Repository jupyterhub/kubespawner, pull requests merged in 2023-09, with the labels that each got.

#774 Rework of profile_list backend validation for readability and details
  kubespawner/spawner.py
  tests/test_profile.py
Labels: maintenance

#777 Allow dropdown text for unlisted choice to be configurable
  kubespawner/spawner.py
  kubespawner/templates/form.html
  tests/test_profile.py
Labels: new

#785 Support lists and dicts as values in `kubespawner_override`
  kubespawner/spawner.py
  kubespawner/utils.py
  tests/test_profile.py
Labels: bug

#768 Add changelog for 6.1.0
  docs/source/changelog.md
Labels: documentation
