Repository jupyterhub/kubespawner, pull requests merged in 2023-05, with the labels that each got.

#726 Require jupyterhub 4+, currently latest kubernetes_asyncio, and stop testing k8s 1.23
  .github/workflows/test.yaml
  docs/source/changelog.md
  pyproject.toml
Labels: maintenance, breaking

#724 Allow building more complex profile_list templates
  .pre-commit-config.yaml
  MANIFEST.in
  kubespawner/spawner.py
  kubespawner/templates/form.html
  kubespawner/templates/style.css
  pyproject.toml
Labels: new

#733 Update Readme badges & requirements
  README.md
Labels: documentation

#729 Select profile if any of its choices are interacted with
  kubespawner/templates/form.html
Labels: bug

#739 Add changelog for 6.0.0
  docs/source/changelog.md
Labels: documentation
