Repository jupyterhub/kubespawner, pull requests merged in 2024-10, with the labels that each got.

#856 fix some safe slug patterns
  kubespawner/slugs.py
  kubespawner/spawner.py
  tests/test_slugs.py
  tests/test_spawner.py
Labels: bug

#857 changelog for 7.0.0b2
  docs/source/changelog.md
Labels: documentation

#859 Reflectors watch: close after stop
  kubespawner/reflector.py
Labels: bug

#860 await asyncio.ensure_future
  kubespawner/spawner.py
Labels: bug

#862 Make changelog links consistent
  docs/source/changelog.md
Labels: documentation

#865 Add escape_slug as a utility function alongside safe_slug
  kubespawner/proxy.py
  kubespawner/slugs.py
  kubespawner/spawner.py
Labels: new

#866 Add changelog for 7.0.0
  docs/source/changelog.md
Labels: documentation
